.PHONY: resume

DATE=`date +'%Y-%m-%d'`

resume:
	cp Resume.pdf ~/Desktop/Su_Christopher_Resume.pdf
	cp Resume.pdf ~/Dropbox/Public/Resume.pdf
	cp Resume.pdf ~/Dropbox/Public/Su_Christopher_Resume.pdf
	cp Resume.pdf ~/Code/csu.github.io/Su_Christopher_Resume.pdf
	cp Resume.pdf Resume-$(DATE).pdf
	cd ~/Code/csu.github.io && git add Su_Christopher_Resume.pdf && git commit -m "resume" && git push
