#!/bin/bash
DEST="rsync://bastion.local/backup-xps-linux/latest"
EXCLUDE_FILE="/home/csu/bin/backup-exclude.txt"

# Dry run:
# rsync -aAXv --dry-run --delete --exclude-from "$EXCLUDE_FILE" / $DEST

# Actual backup:
rsync -aAX --info=progress2 --delete --exclude-from "$EXCLUDE_FILE" / $DEST
